// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package message;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code message.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Request = 0;</code>
     */
    Request(0),
    /**
     * <code>Response = 1;</code>
     */
    Response(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Request = 0;</code>
     */
    public static final int Request_VALUE = 0;
    /**
     * <code>Response = 1;</code>
     */
    public static final int Response_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return Request;
        case 1: return Response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.RequestType)
  }

  /**
   * Protobuf enum {@code message.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Pong = 0;</code>
     */
    Pong(0),
    /**
     * <pre>
     * 握手
     * </pre>
     *
     * <code>Handshake = 1;</code>
     */
    Handshake(1),
    /**
     * <pre>
     * 上线
     * </pre>
     *
     * <code>Online = 2;</code>
     */
    Online(2),
    /**
     * <pre>
     * 下线
     * </pre>
     *
     * <code>Offline = 3;</code>
     */
    Offline(3),
    /**
     * <pre>
     * 文件传输
     * </pre>
     *
     * <code>File = 4;</code>
     */
    File(4),
    /**
     * <pre>
     * 群发消息
     * </pre>
     *
     * <code>GroupMessage = 5;</code>
     */
    GroupMessage(5),
    /**
     * <pre>
     * 私聊消息
     * </pre>
     *
     * <code>PrivateMessage = 6;</code>
     */
    PrivateMessage(6),
    /**
     * <pre>
     * 系统广播
     * </pre>
     *
     * <code>SystemBroadcast = 7;</code>
     */
    SystemBroadcast(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Pong = 0;</code>
     */
    public static final int Pong_VALUE = 0;
    /**
     * <pre>
     * 握手
     * </pre>
     *
     * <code>Handshake = 1;</code>
     */
    public static final int Handshake_VALUE = 1;
    /**
     * <pre>
     * 上线
     * </pre>
     *
     * <code>Online = 2;</code>
     */
    public static final int Online_VALUE = 2;
    /**
     * <pre>
     * 下线
     * </pre>
     *
     * <code>Offline = 3;</code>
     */
    public static final int Offline_VALUE = 3;
    /**
     * <pre>
     * 文件传输
     * </pre>
     *
     * <code>File = 4;</code>
     */
    public static final int File_VALUE = 4;
    /**
     * <pre>
     * 群发消息
     * </pre>
     *
     * <code>GroupMessage = 5;</code>
     */
    public static final int GroupMessage_VALUE = 5;
    /**
     * <pre>
     * 私聊消息
     * </pre>
     *
     * <code>PrivateMessage = 6;</code>
     */
    public static final int PrivateMessage_VALUE = 6;
    /**
     * <pre>
     * 系统广播
     * </pre>
     *
     * <code>SystemBroadcast = 7;</code>
     */
    public static final int SystemBroadcast_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return Pong;
        case 1: return Handshake;
        case 2: return Online;
        case 3: return Offline;
        case 4: return File;
        case 5: return GroupMessage;
        case 6: return PrivateMessage;
        case 7: return SystemBroadcast;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MessageOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.MessageType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>.message.MessageType cmd = 2;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <code>.message.MessageType cmd = 2;</code>
     * @return The cmd.
     */
    MessageType getCmd();

    /**
     * <code>int64 form_id = 3;</code>
     * @return The formId.
     */
    long getFormId();

    /**
     * <code>int64 to_id = 4;</code>
     * @return The toId.
     */
    long getToId();

    /**
     * <code>int64 create_time = 5;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>bytes body = 6;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <code>int32 length = 7;</code>
     * @return The length.
     */
    int getLength();
  }
  /**
   * Protobuf type {@code message.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      cmd_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 24: {

              formId_ = input.readInt64();
              break;
            }
            case 32: {

              toId_ = input.readInt64();
              break;
            }
            case 40: {

              createTime_ = input.readInt64();
              break;
            }
            case 50: {

              body_ = input.readBytes();
              break;
            }
            case 56: {

              length_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_message_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_message_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>.message.MessageType cmd = 2;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    @Override public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.message.MessageType cmd = 2;</code>
     * @return The cmd.
     */
    @Override public MessageType getCmd() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(cmd_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int FORM_ID_FIELD_NUMBER = 3;
    private long formId_;
    /**
     * <code>int64 form_id = 3;</code>
     * @return The formId.
     */
    @Override
    public long getFormId() {
      return formId_;
    }

    public static final int TO_ID_FIELD_NUMBER = 4;
    private long toId_;
    /**
     * <code>int64 to_id = 4;</code>
     * @return The toId.
     */
    @Override
    public long getToId() {
      return toId_;
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <code>int64 create_time = 5;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 6;</code>
     * @return The body.
     */
    @Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int LENGTH_FIELD_NUMBER = 7;
    private int length_;
    /**
     * <code>int32 length = 7;</code>
     * @return The length.
     */
    @Override
    public int getLength() {
      return length_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (cmd_ != MessageType.Pong.getNumber()) {
        output.writeEnum(2, cmd_);
      }
      if (formId_ != 0L) {
        output.writeInt64(3, formId_);
      }
      if (toId_ != 0L) {
        output.writeInt64(4, toId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(5, createTime_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(6, body_);
      }
      if (length_ != 0) {
        output.writeInt32(7, length_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (cmd_ != MessageType.Pong.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmd_);
      }
      if (formId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, formId_);
      }
      if (toId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, toId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, body_);
      }
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (getId()
          != other.getId()) return false;
      if (cmd_ != other.cmd_) return false;
      if (getFormId()
          != other.getFormId()) return false;
      if (getToId()
          != other.getToId()) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (getLength()
          != other.getLength()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + FORM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFormId());
      hash = (37 * hash) + TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToId());
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_message_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_message_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using message.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        cmd_ = 0;

        formId_ = 0L;

        toId_ = 0L;

        createTime_ = 0L;

        body_ = com.google.protobuf.ByteString.EMPTY;

        length_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_message_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.id_ = id_;
        result.cmd_ = cmd_;
        result.formId_ = formId_;
        result.toId_ = toId_;
        result.createTime_ = createTime_;
        result.body_ = body_;
        result.length_ = length_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getFormId() != 0L) {
          setFormId(other.getFormId());
        }
        if (other.getToId() != 0L) {
          setToId(other.getToId());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.message.MessageType cmd = 2;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      @Override public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.message.MessageType cmd = 2;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.MessageType cmd = 2;</code>
       * @return The cmd.
       */
      @Override
      public MessageType getCmd() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(cmd_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.MessageType cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.MessageType cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private long formId_ ;
      /**
       * <code>int64 form_id = 3;</code>
       * @return The formId.
       */
      @Override
      public long getFormId() {
        return formId_;
      }
      /**
       * <code>int64 form_id = 3;</code>
       * @param value The formId to set.
       * @return This builder for chaining.
       */
      public Builder setFormId(long value) {
        
        formId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 form_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormId() {
        
        formId_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <code>int64 to_id = 4;</code>
       * @return The toId.
       */
      @Override
      public long getToId() {
        return toId_;
      }
      /**
       * <code>int64 to_id = 4;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(long value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        
        toId_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 create_time = 5;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 create_time = 5;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 create_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 6;</code>
       * @return The body.
       */
      @Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 6;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>int32 length = 7;</code>
       * @return The length.
       */
      @Override
      public int getLength() {
        return length_;
      }
      /**
       * <code>int32 length = 7;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 length = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Message)
    }

    // @@protoc_insertion_point(class_scope:message.Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.MessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.message.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.message.RequestType type = 1;</code>
     * @return The type.
     */
    RequestType getType();

    /**
     * <code>.message.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.message.Message message = 2;</code>
     * @return The message.
     */
    Message getMessage();
    /**
     * <code>.message.Message message = 2;</code>
     */
    MessageOrBuilder getMessageOrBuilder();

    /**
     * <code>.message.Reply response = 3;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.message.Reply response = 3;</code>
     * @return The response.
     */
    Reply getResponse();
    /**
     * <code>.message.Reply response = 3;</code>
     */
    ReplyOrBuilder getResponseOrBuilder();

    public MessageRequest.PackCase getPackCase();
  }
  /**
   * Protobuf type {@code message.MessageRequest}
   */
  public static final class MessageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.MessageRequest)
      MessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageRequest.newBuilder() to construct.
    private MessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageRequest() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              Message.Builder subBuilder = null;
              if (packCase_ == 2) {
                subBuilder = ((Message) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Message) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 2;
              break;
            }
            case 26: {
              Reply.Builder subBuilder = null;
              if (packCase_ == 3) {
                subBuilder = ((Reply) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(Reply.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Reply) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_message_MessageRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_message_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageRequest.class, Builder.class);
    }

    private int packCase_ = 0;
    private Object pack_;
    public enum PackCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      MESSAGE(2),
      RESPONSE(3),
      PACK_NOT_SET(0);
      private final int value;
      private PackCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PackCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackCase forNumber(int value) {
        switch (value) {
          case 2: return MESSAGE;
          case 3: return RESPONSE;
          case 0: return PACK_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackCase
    getPackCase() {
      return PackCase.forNumber(
          packCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.message.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.message.RequestType type = 1;</code>
     * @return The type.
     */
    @Override public RequestType getType() {
      @SuppressWarnings("deprecation")
      RequestType result = RequestType.valueOf(type_);
      return result == null ? RequestType.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.message.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    @Override
    public boolean hasMessage() {
      return packCase_ == 2;
    }
    /**
     * <code>.message.Message message = 2;</code>
     * @return The message.
     */
    @Override
    public Message getMessage() {
      if (packCase_ == 2) {
         return (Message) pack_;
      }
      return Message.getDefaultInstance();
    }
    /**
     * <code>.message.Message message = 2;</code>
     */
    @Override
    public MessageOrBuilder getMessageOrBuilder() {
      if (packCase_ == 2) {
         return (Message) pack_;
      }
      return Message.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>.message.Reply response = 3;</code>
     * @return Whether the response field is set.
     */
    @Override
    public boolean hasResponse() {
      return packCase_ == 3;
    }
    /**
     * <code>.message.Reply response = 3;</code>
     * @return The response.
     */
    @Override
    public Reply getResponse() {
      if (packCase_ == 3) {
         return (Reply) pack_;
      }
      return Reply.getDefaultInstance();
    }
    /**
     * <code>.message.Reply response = 3;</code>
     */
    @Override
    public ReplyOrBuilder getResponseOrBuilder() {
      if (packCase_ == 3) {
         return (Reply) pack_;
      }
      return Reply.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != RequestType.Request.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (packCase_ == 2) {
        output.writeMessage(2, (Message) pack_);
      }
      if (packCase_ == 3) {
        output.writeMessage(3, (Reply) pack_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != RequestType.Request.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (packCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Message) pack_);
      }
      if (packCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Reply) pack_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageRequest)) {
        return super.equals(obj);
      }
      MessageRequest other = (MessageRequest) obj;

      if (type_ != other.type_) return false;
      if (!getPackCase().equals(other.getPackCase())) return false;
      switch (packCase_) {
        case 2:
          if (!getMessage()
              .equals(other.getMessage())) return false;
          break;
        case 3:
          if (!getResponse()
              .equals(other.getResponse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (packCase_) {
        case 2:
          hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.MessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.MessageRequest)
        MessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_message_MessageRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_message_MessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageRequest.class, Builder.class);
      }

      // Construct using message.MessageOuterClass.MessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        packCase_ = 0;
        pack_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_message_MessageRequest_descriptor;
      }

      @Override
      public MessageRequest getDefaultInstanceForType() {
        return MessageRequest.getDefaultInstance();
      }

      @Override
      public MessageRequest build() {
        MessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageRequest buildPartial() {
        MessageRequest result = new MessageRequest(this);
        result.type_ = type_;
        if (packCase_ == 2) {
          if (messageBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = messageBuilder_.build();
          }
        }
        if (packCase_ == 3) {
          if (responseBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = responseBuilder_.build();
          }
        }
        result.packCase_ = packCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageRequest) {
          return mergeFrom((MessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageRequest other) {
        if (other == MessageRequest.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getPackCase()) {
          case MESSAGE: {
            mergeMessage(other.getMessage());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case PACK_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packCase_ = 0;
      private Object pack_;
      public PackCase
          getPackCase() {
        return PackCase.forNumber(
            packCase_);
      }

      public Builder clearPack() {
        packCase_ = 0;
        pack_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.message.RequestType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.message.RequestType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.RequestType type = 1;</code>
       * @return The type.
       */
      @Override
      public RequestType getType() {
        @SuppressWarnings("deprecation")
        RequestType result = RequestType.valueOf(type_);
        return result == null ? RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.RequestType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.RequestType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Message, Message.Builder, MessageOrBuilder> messageBuilder_;
      /**
       * <code>.message.Message message = 2;</code>
       * @return Whether the message field is set.
       */
      @Override
      public boolean hasMessage() {
        return packCase_ == 2;
      }
      /**
       * <code>.message.Message message = 2;</code>
       * @return The message.
       */
      @Override
      public Message getMessage() {
        if (messageBuilder_ == null) {
          if (packCase_ == 2) {
            return (Message) pack_;
          }
          return Message.getDefaultInstance();
        } else {
          if (packCase_ == 2) {
            return messageBuilder_.getMessage();
          }
          return Message.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      public Builder setMessage(Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      public Builder setMessage(
          Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      public Builder mergeMessage(Message value) {
        if (messageBuilder_ == null) {
          if (packCase_ == 2 &&
              pack_ != Message.getDefaultInstance()) {
            pack_ = Message.newBuilder((Message) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 2) {
            messageBuilder_.mergeFrom(value);
          }
          messageBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
          }
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      public Message.Builder getMessageBuilder() {
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      @Override
      public MessageOrBuilder getMessageOrBuilder() {
        if ((packCase_ == 2) && (messageBuilder_ != null)) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 2) {
            return (Message) pack_;
          }
          return Message.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Message message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Message, Message.Builder, MessageOrBuilder>
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          if (!(packCase_ == 2)) {
            pack_ = Message.getDefaultInstance();
          }
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Message, Message.Builder, MessageOrBuilder>(
                  (Message) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 2;
        onChanged();;
        return messageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Reply, Reply.Builder, ReplyOrBuilder> responseBuilder_;
      /**
       * <code>.message.Reply response = 3;</code>
       * @return Whether the response field is set.
       */
      @Override
      public boolean hasResponse() {
        return packCase_ == 3;
      }
      /**
       * <code>.message.Reply response = 3;</code>
       * @return The response.
       */
      @Override
      public Reply getResponse() {
        if (responseBuilder_ == null) {
          if (packCase_ == 3) {
            return (Reply) pack_;
          }
          return Reply.getDefaultInstance();
        } else {
          if (packCase_ == 3) {
            return responseBuilder_.getMessage();
          }
          return Reply.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      public Builder setResponse(Reply value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      public Builder setResponse(
          Reply.Builder builderForValue) {
        if (responseBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      public Builder mergeResponse(Reply value) {
        if (responseBuilder_ == null) {
          if (packCase_ == 3 &&
              pack_ != Reply.getDefaultInstance()) {
            pack_ = Reply.newBuilder((Reply) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 3) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      public Reply.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      @Override
      public ReplyOrBuilder getResponseOrBuilder() {
        if ((packCase_ == 3) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 3) {
            return (Reply) pack_;
          }
          return Reply.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Reply response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Reply, Reply.Builder, ReplyOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(packCase_ == 3)) {
            pack_ = Reply.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Reply, Reply.Builder, ReplyOrBuilder>(
                  (Reply) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 3;
        onChanged();;
        return responseBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.MessageRequest)
    }

    // @@protoc_insertion_point(class_scope:message.MessageRequest)
    private static final MessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageRequest();
    }

    public static MessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageRequest>() {
      @Override
      public MessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>int64 msg_id = 2;</code>
     * @return The msgId.
     */
    long getMsgId();

    /**
     * <code>bytes body = 3;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code message.Reply}
   */
  public static final class Reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Reply)
      ReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reply() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Reply();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 16: {

              msgId_ = input.readInt64();
              break;
            }
            case 26: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_message_Reply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_message_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Reply.class, Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 2;
    private long msgId_;
    /**
     * <code>int64 msg_id = 2;</code>
     * @return The msgId.
     */
    @Override
    public long getMsgId() {
      return msgId_;
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 3;</code>
     * @return The body.
     */
    @Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(2, msgId_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(3, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgId_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Reply)) {
        return super.equals(obj);
      }
      Reply other = (Reply) obj;

      if (getCode()
          != other.getCode()) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Reply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Reply)
        ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_message_Reply_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_message_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Reply.class, Builder.class);
      }

      // Construct using message.MessageOuterClass.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msgId_ = 0L;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_message_Reply_descriptor;
      }

      @Override
      public Reply getDefaultInstanceForType() {
        return Reply.getDefaultInstance();
      }

      @Override
      public Reply build() {
        Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Reply buildPartial() {
        Reply result = new Reply(this);
        result.code_ = code_;
        result.msgId_ = msgId_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Reply) {
          return mergeFrom((Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Reply other) {
        if (other == Reply.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <code>int64 msg_id = 2;</code>
       * @return The msgId.
       */
      @Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msg_id = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msg_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 3;</code>
       * @return The body.
       */
      @Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 3;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Reply)
    }

    // @@protoc_insertion_point(class_scope:message.Reply)
    private static final Reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Reply();
    }

    public static Reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reply>
        PARSER = new com.google.protobuf.AbstractParser<Reply>() {
      @Override
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reply> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    @Override
    public Reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\213\001\n\007Message\022\n\n\002" +
      "id\030\001 \001(\003\022!\n\003cmd\030\002 \001(\0162\024.message.MessageT" +
      "ype\022\017\n\007form_id\030\003 \001(\003\022\r\n\005to_id\030\004 \001(\003\022\023\n\013c" +
      "reate_time\030\005 \001(\003\022\014\n\004body\030\006 \001(\014\022\016\n\006length" +
      "\030\007 \001(\005\"\205\001\n\016MessageRequest\022\"\n\004type\030\001 \001(\0162" +
      "\024.message.RequestType\022#\n\007message\030\002 \001(\0132\020" +
      ".message.MessageH\000\022\"\n\010response\030\003 \001(\0132\016.m" +
      "essage.ReplyH\000B\006\n\004pack\"3\n\005Reply\022\014\n\004code\030" +
      "\001 \001(\005\022\016\n\006msg_id\030\002 \001(\003\022\014\n\004body\030\003 \001(\014*(\n\013R" +
      "equestType\022\013\n\007Request\020\000\022\014\n\010Response\020\001*\204\001" +
      "\n\013MessageType\022\010\n\004Pong\020\000\022\r\n\tHandshake\020\001\022\n" +
      "\n\006Online\020\002\022\013\n\007Offline\020\003\022\010\n\004File\020\004\022\020\n\014Gro" +
      "upMessage\020\005\022\022\n\016PrivateMessage\020\006\022\023\n\017Syste" +
      "mBroadcast\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Message_descriptor,
        new String[] { "Id", "Cmd", "FormId", "ToId", "CreateTime", "Body", "Length", });
    internal_static_message_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageRequest_descriptor,
        new String[] { "Type", "Message", "Response", "Pack", });
    internal_static_message_Reply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Reply_descriptor,
        new String[] { "Code", "MsgId", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
